//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class forgotpass
    {
        public int Id { get; set; }
        public string Uid { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ReqDateTime { get; set; }
    }
}
