//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string projectname { get; set; }
        public string projectdetails { get; set; }
        public string projecturl { get; set; }
    }
}
