//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resume_Builder
{
    using System;
    using System.Collections.Generic;
    
    public partial class resumedata
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string mobileno { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string maritalstatus { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string ustate { get; set; }
        public string ucity { get; set; }
        public string school { get; set; }
        public string university { get; set; }
        public string qualification { get; set; }
        public string branch { get; set; }
        public string passingyear { get; set; }
        public string cgpa { get; set; }
        public string currentstudy { get; set; }
        public string jobtitle { get; set; }
        public string employeer { get; set; }
        public string wcity { get; set; }
        public string wstate { get; set; }
        public Nullable<System.DateTime> startyear { get; set; }
        public Nullable<System.DateTime> endyear { get; set; }
        public string currentjob { get; set; }
        public string carrerobj { get; set; }
        public string summary { get; set; }
        public string imagepath { get; set; }
    }
}
